name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Fix Permissions and Dependencies
        run: |
          flutter pub get
          cd android
          chmod +x gradlew
          
      - name: Build APK
        # यहाँ हम पुरानी सेटिंग्स को दरकिनार करने के लिए कमांड बदल रहे हैं
        run: flutter build apk --release --no-tree-shake-icons --split-debug-info=build/app/outputs/symbols
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartSave-App
          path: build/app/outputs/flutter-apk/app-release.apk
