name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Force Update Gradle and Build
        run: |
          flutter pub get
          cd android
          # पुरानी सेटिंग्स को साफ़ करने के लिए
          ./gradlew clean 
          # जबरदस्ती नया वर्जन इस्तेमाल करने के लिए
          ./gradlew assembleRelease --stacktrace 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartSave-App
          path: build/app/outputs/flutter-apk/app-release.apk
